# Pytorch Learning

### CH1. Tensor Manipulation - Part 1

#### 1. Similarity to Numpy

In [5]:
import numpy as np

#### (1) 1D with Numpy

In [13]:
arr = np.array([0.,1.,2.,3.,4.,5.,6.])
print(arr)

[0. 1. 2. 3. 4. 5. 6.]


In [33]:
# Rank & Shape of 1D array
print("Rank of array : ", arr.ndim) ## Rank = Dimension
print("Shape of array : ", arr.shape) ## (7,) means (1,7)
print("Number of components in array : ", arr.size)

Rank of array :  1
Shape of array :  (7,)
Number of components in array :  7


In [27]:
# Components of 1D array
## Note that at Python range (a,b) : a 이상 b 미만
for i in range(0,7):
    print(arr[i])
print("---------------------------")
print(arr[-1]) ## Component num. -1 means last num.
print("---------------------------")
print(arr[0:2]) 
print(arr[2:-1])
print(arr[:5]) ## Start from beginning
print(arr[2:]) ## Stop at end

0.0
1.0
2.0
3.0
4.0
5.0
6.0
---------------------------
6.0
---------------------------
[0. 1.]
[2. 3. 4. 5.]
[0. 1. 2. 3. 4.]
[2. 3. 4. 5. 6.]


#### (2) 2D with Numpy

In [29]:
arr_2 = np.array([[0.,1.,2.],[3.,4.,5.]])
print(arr_2)

[[0. 1. 2.]
 [3. 4. 5.]]


In [30]:
# Rank & Shape of 2D array
print("Rank of array : ", arr_2.ndim)
print("Shape of array : ", arr_2.shape)

Rank of array :  2
Shape of array :  (2, 3)


#### 2. Tensor Allocation

In [3]:
import torch

#### (1) 1D with Pytorch

In [35]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [45]:
print("Rank of tensor : ", t.dim())
print("Shape of tensor : ", t.shape)
print("Shape of tensor : ", t.size()) ## This result is same as the result of t.shape

Rank of tensor :  1
Shape of tensor :  torch.Size([7])
Shape of tensor :  torch.Size([7])


#### (2) 2D with Pytorch

In [49]:
t_2 = torch.FloatTensor([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0],[10.0,11.0,12.0]])
print(t_2)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [53]:
print("Rank of tensor : ", t_2.dim())
print("Shape of tensor : ", t_2.shape)
print("Shape of tensor : ", t_2.size())

Rank of tensor :  2
Shape of tensor :  torch.Size([4, 3])
Shape of tensor :  torch.Size([4, 3])


In [64]:
# Slicing
print(t_2[:,:])
print(t_2[:2, :2])
print(t_2[1:3, :])
## t_2[Row_index, Column_index]

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2.],
        [4., 5.]])
tensor([[4., 5., 6.],
        [7., 8., 9.]])


#### 3. Handling Tensors

#### (1) Broadcasting

In [79]:
# For addtion, and subtraction, two matrices' size should be same
# However, in Pytorch, it can automatically fit their size using Broadcasting
# Warning! Be sure with your tensor's size
tensor1 = torch.FloatTensor([[1, 2, 3],[4, 5, 6]]) ## Size : 2 x 3
tensor2 = torch.FloatTensor([[1],[2]]) ## Size : 3 x 1
print("tensor1 : ", tensor1)
print(tensor1.size())
print("--------------------")
print("tensor2 : ", tensor2)
print(tensor2.size())
print("--------------------")
print("Broadcasting: ", tensor1 + tensor2)

## Rules for Broadcasting
## 1. Each tensor has at least one dimension
## 2. Comparing the dimension sizes of each tensors...
### (1) the dimension sizes are equal
### (2) one of the dimension sizes is 1
### (3) one of the dimension sizes does not exist

tensor1 :  tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
--------------------
tensor2 :  tensor([[1.],
        [2.]])
torch.Size([2, 1])
--------------------
Broadcasting:  tensor([[2., 3., 4.],
        [6., 7., 8.]])


#### (2) Matrix Multiplication & Multiplication

In [89]:
tensor1 = torch.FloatTensor([[1, 2],[4, 5]]) ## Size : 2 x 2
tensor2 = torch.FloatTensor([[1],[2]]) ## Size : 2 x 1
print(tensor1.matmul(tensor2)) ## Size : 2 x 1
print(tensor1 * tensor2) ## Size : 2 x 2
print(tensor1.mul(tensor2)) ## This result is same as the result of *

## Rules for Element-wise multiplication
## 1. Each tensor has at least one dimension
## 2. Comparing the dimension sizes of each tensors...
### (1) the dimension sizes are equal
### (2) one of the dimension sizes is 1
### (3) one of the dimension sizes does not exist

tensor([[ 5.],
        [14.]])
tensor([[ 1.,  2.],
        [ 8., 10.]])
tensor([[ 1.,  2.],
        [ 8., 10.]])


#### (3) Mean

In [112]:
tensor1 = torch.FloatTensor([1, 2]) # 1D Size : 1 x 2
tensor2 = torch.FloatTensor([[1, 2],[3, 4]]) # 2D Size : 2 x 2
print(tensor1)
print(tensor2)
print("--------------------")
print(tensor1.mean())
print(tensor1.mean().size()) ## mean value of tensor is also tensor
print("--------------------")
print(tensor2.mean())
print(tensor2.mean().size())
print("--------------------")
print(tensor2.mean(dim=0)) ## dim=0 for Column => Reduce the dimension of Column
print(tensor2.mean(dim=1)) ## dim=1 for Row => Reduce the dimension of Row
print(tensor2.mean(dim=-1))

tensor([1., 2.])
tensor([[1., 2.],
        [3., 4.]])
--------------------
tensor(1.5000)
torch.Size([])
--------------------
tensor(2.5000)
torch.Size([])
--------------------
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


#### (4) Sum

In [8]:
tensor1 = torch.FloatTensor([1, 2]) # 1D Size : 1 x 2
tensor2 = torch.FloatTensor([[1, 2],[3, 4]]) # 2D Size : 2 x 2
print(tensor1)
print(tensor2)
print("--------------------")
print(tensor1.sum())
print(tensor1.sum().size()) ## mean value of tensor is also tensor
print("--------------------")
print(tensor2.sum())
print(tensor2.sum().size())
print("--------------------")
print(tensor2.sum(dim=0)) ## dim=0 for Column => Reduce the dimension of Column
print(tensor2.sum(axis=0))
print(tensor2.sum(dim=1)) ## dim=1 for Row => Reduce the dimension of Row
print(tensor2.sum(dim=-1))

tensor([1., 2.])
tensor([[1., 2.],
        [3., 4.]])
--------------------
tensor(3.)
torch.Size([])
--------------------
tensor(10.)
torch.Size([])
--------------------
tensor([4., 6.])
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


#### (5) Max & Argmax

In [9]:
t = torch.FloatTensor([[1, 2],[3, 4]])
print(t)
print("--------------------")
print(t.max())
print("--------------------")
print(t.max(dim=0))
print(t.max(dim=0)[0]) ## Values
print(t.max(dim=0)[1]) ## Indices
print("--------------------")
print(t.argmax())
print(t.argmax(dim=0)) ## Result is same as the one from t.max(dim=0)[1]

tensor([[1., 2.],
        [3., 4.]])
--------------------
tensor(4.)
--------------------
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
tensor([3., 4.])
tensor([1, 1])
--------------------
tensor(3)
tensor([1, 1])


#### (※) Dimension of Arrays

In [32]:
t2 = torch.FloatTensor([[0, 1, 2],[3, 4, 5]])
print(t2.shape)
print(t2)
print("--------------------")
print("[dim=0]")
print(t2.sum(dim=0).shape)
print(t2.sum(dim=0))
print("--------------------")
print("[dim=1]")
print(t2.sum(dim=1).shape)
print(t2.sum(dim=1))

torch.Size([2, 3])
tensor([[0., 1., 2.],
        [3., 4., 5.]])
--------------------
[dim=0]
torch.Size([3])
tensor([3., 5., 7.])
--------------------
[dim=1]
torch.Size([2])
tensor([ 3., 12.])


In [33]:
t3 = torch.FloatTensor([[[0, 1, 2],[3, 4, 5]],[[0, 1, 2],[3, 4, 5]],[[0, 1, 2],[3, 4, 5]]])
print(t3.shape)
print(t3)
print("--------------------")
print("[dim=0]")
print(t3.sum(dim=0).shape)
print(t3.sum(dim=0))
print("--------------------")
print("[dim=1]")
print(t3.sum(dim=1).shape)
print(t3.sum(dim=1))
print("--------------------")
print("[dim=2]")
print(t3.sum(dim=2).shape)
print(t3.sum(dim=2))

torch.Size([3, 2, 3])
tensor([[[0., 1., 2.],
         [3., 4., 5.]],

        [[0., 1., 2.],
         [3., 4., 5.]],

        [[0., 1., 2.],
         [3., 4., 5.]]])
--------------------
[dim=0]
torch.Size([2, 3])
tensor([[ 0.,  3.,  6.],
        [ 9., 12., 15.]])
--------------------
[dim=1]
torch.Size([3, 3])
tensor([[3., 5., 7.],
        [3., 5., 7.],
        [3., 5., 7.]])
--------------------
[dim=2]
torch.Size([3, 2])
tensor([[ 3., 12.],
        [ 3., 12.],
        [ 3., 12.]])
