### CH1. Tensor Manipulation - Part 2

#### 3. Handling Tensors

In [1]:
import torch

#### (6) View

In [2]:
t3 = torch.FloatTensor([[[0, 1, 2],[3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
print(t3)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [3]:
# Both output size of Tensor
print(t3.size())
print(t3.shape)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])


In [4]:
# Reshape into 2D Tensor
print(t3.view([-1,3])) ## -1 means reshape automatically (Leave it to Pytorch)
print(t3.view([2,6])) ## Shape must be maintained (2x2x3)=(2x6)=12

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])


In [5]:
# Reshape into 3D Tensor
print(t3.view([-1,2,3])) ## -1 means reshape automatically (Leave it to Pytorch)
print(t3.view([2,3,2])) ## Shape must be maintained (2x2x3)=(2x3x2)=12

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.]],

        [[ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]]])


#### (7) Squeeze & Unsqueeze

In [6]:
t2 = torch.FloatTensor([[0],[1],[2]])
print(t2)

tensor([[0.],
        [1.],
        [2.]])


In [7]:
print(t2.size())

torch.Size([3, 1])


In [8]:
# Squeeze
# Eliminate the dimension with 1 == Reduce total dimensions
print(t2.squeeze())
print(t2.squeeze().size())

tensor([0., 1., 2.])
torch.Size([3])


In [9]:
t1 = t2.squeeze()
print(t1)

tensor([0., 1., 2.])


In [10]:
print(t1.size())

torch.Size([3])


In [11]:
# Unsqueeze
# Add the dimension with 1 at specific place == increase total dimensions
print(t1.unsqueeze(dim=0).size())
print(t1.unsqueeze(dim=0))
print("--------------------------")
print(t1.unsqueeze(dim=1).size())
print(t1.unsqueeze(dim=1))

torch.Size([1, 3])
tensor([[0., 1., 2.]])
--------------------------
torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])


#### (8) Concatenate & Stack

In [12]:
# Concatenate
## Non-empty tensors provided must have the same shape, except in the cat dimension
x = torch.randint(high=10, size=(2,2))
y = torch.randint(high=10, size=(2,2))
print(x)
print(y)

tensor([[7, 8],
        [3, 8]])
tensor([[5, 6],
        [5, 2]])


In [13]:
print(torch.cat([x,y]))
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[7, 8],
        [3, 8],
        [5, 6],
        [5, 2]])
tensor([[7, 8],
        [3, 8],
        [5, 6],
        [5, 2]])
tensor([[7, 8, 5, 6],
        [3, 8, 5, 2]])


In [14]:
# Stack == concatenate + unsqueeze
## Concatenate a sequence of tensors along a new dimension
## All tensors need to be of the same size
x = torch.randint(high=10, size=(2,2))
y = torch.randint(high=10, size=(2,2))
z = torch.randint(high=10, size=(2,2))
print(x)
print(y)
print(z)

tensor([[7, 8],
        [7, 6]])
tensor([[4, 3],
        [8, 8]])
tensor([[1, 6],
        [3, 7]])


In [15]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=0))
print(torch.stack([x,y,z], dim=1))
print(torch.stack([x,y,z], dim=2))

tensor([[[7, 8],
         [7, 6]],

        [[4, 3],
         [8, 8]],

        [[1, 6],
         [3, 7]]])
tensor([[[7, 8],
         [7, 6]],

        [[4, 3],
         [8, 8]],

        [[1, 6],
         [3, 7]]])
tensor([[[7, 8],
         [4, 3],
         [1, 6]],

        [[7, 6],
         [8, 8],
         [3, 7]]])
tensor([[[7, 4, 1],
         [8, 3, 6]],

        [[7, 8, 3],
         [6, 8, 7]]])


#### (9) ones_like & zeros_like

In [16]:
x = torch.randint(high=10, size=(2,3))
print(x)

tensor([[7, 4, 8],
        [6, 8, 6]])


In [17]:
# ones_like
## _like means same size with tensor x
t1 = torch.ones_like(x)
print(t1)
# ones
t1_1 = torch.ones(size=(2,3))
print(t1_1)

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [18]:
# zeros_like
## _like means same size with tensor x
t0 = torch.zeros_like(x)
print(t0)
# zeros
t0_1 = torch.zeros(size=(2,3))
print(t0_1)

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### (10) In-place operation

In [19]:
x = torch.FloatTensor([[1, 2],[3, 4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [21]:
print(x.mul(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [22]:
## In-place operation saves its result into variable
print(x.mul_(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
